#!/bin/sh

DOTFILES_ROOT="`pwd`"

echo ''

info() {
  printf "[ \033[00;34m..\033[0m ] $1\n"
}

success() {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

link_files() {
  ln -s $1 $2
  success "linked $1 to $2"
}

install_dotfiles() {
  link_files $DOTFILES_ROOT/templates/config.fish ~/.config/fish/config.fish

  for df in $DOTFILES_ROOT/templates/.*; do
    if [ -f $df ]; then
      link_files $df ~/
    fi
  done
}

initialize_environment() {
  # Handle line breaks correctly
  git config --global core.autocrlf input

  if [ ! -d "~/.config/fish" ] ; then
    mkdir -p ~/.config/fish
  fi
}

info 'Looking for Fish'

# Check to see if fish is installed
if hash fish 2>/dev/null; then
  success 'Fish Found - Lets get swimming'
else
  info 'Installing Fish'

  if [ "$(uname -s)" == "Darwin" ]
  then
    brew install fish
  else
    # This only works for ubuntu
    sudo apt-add-repository ppa:fish-shell/release-2
    sudo apt-get update
    sudo apt-get install fish
  fi

  success 'Fish Installed'

fi

if hash hub 2>/dev/null; then
  success 'Hub Found...'
else
  info 'Installing Hub'

  if [ "$(uname -s)" == "Darwin" ]
  then
    brew install hub
  fi
fi

if hash rbenv 2>/dev/null; then
  success 'Rbenv Found...'
else
  info 'Installing rbenv'

  if [ "$(uname -s)" == "Darwin" ]
  then
    brew install rbenv --HEAD
  fi
fi

info 'Installing Dotfiles'

initialize_environment
install_dotfiles

success 'Done. Get to work!'
