#!/bin/sh

DOTFILES_ROOT="`pwd`"

echo ''

info() {
  printf "[ \033[00;34m..\033[0m ] $1\n"
}

success() {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

link_files() {
  ln -s $1 $2
  success "linked $1 to $2"
}

install_dotfiles() {
  link_files $DOTFILES_ROOT/templates/config.fish ~/.config/fish/config.fish
}

initialize_environment() {
  # Handle line breaks correctly
  git config --global core.autocrlf input

  if [ ! -d "~/.config" || ! -d "~/.config/fish" ]
    mkdir -p ~/.config/fish
  fi
}

info 'Looking for Fish'

# Check to see if fish is installed
if hash fish 2>/dev/null; then
  success 'Fish Found - Lets get swimming'
else
  info 'Installing Fish'

  if [ "$(uname -s)" == "Darwin" ]
  then
    brew install fish
  else
    # This only works for ubuntu
    sudo apt-add-repository ppa:fish-shell/release-2
    sudo apt-get update
    sudo apt-get install fish
  fi

  success 'Fish Installed'

fi

info 'Installing Dotfiles'

initialize_environment
install_dotfiles

success 'Done. Get to work!'

# ln -s $dotfiles_root/templates/config.fish $user_dir/.config/fish/config.fish
